name: macOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'What version to compile and commit to repo?'
        required: true
        default: 0.0.0
        type: number

jobs:
  macos:
    runs-on: macos-latest
    continue-on-error: true
    env:
      VERSION: ${{ github.event.inputs.version }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Setup
        run: |
          brew install ninja
      - name: Configure
        run: |
          curl -L https://github.com/some_repo/some_repo/archive/v${{ env.VERSION }}.tar.gz | tar xzf -
          cd some_repo-${{ env.VERSION }}
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=ON -G Ninja
      - name: Build
        run: |
          cd some_repo-${{ env.VERSION }}
          cmake --build build
          ls -lh build
      - name: Upload/Commit to Repo
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdir -p lib/macOS/
          cp -f some_repo-${{ env.VERSION }}/build/some_repo.1.0.0.dylib lib/macOS/
          git add lib
          git commit -m "created some_repo.1.0.0.dylib - for macOS latest"
          git push -q
